### ISSUE TITLE
ChunkedEncodingError

### ISSUE THREAD

**Issue by pzel** [WallarooLabs/wallaroo_blog_examples#6]
Running the parallel trending hashtags app, I get the following after a while:

```
Traceback (most recent call last):
  File "twitter_client.py", line 50, in <module>
    send_tweets_to_wallaroo(resp,sock)
  File "twitter_client.py", line 18, in send_tweets_to_wallaroo
    for line in http_resp.iter_lines():
  File "/home/p/w/tth/.env/lib/python2.7/site-packages/requests/models.py", line 793, in iter_lines
    for chunk in self.iter_content(chunk_size=chunk_size, decode_unicode=decode_unicode):
  File "/home/p/w/tth/.env/lib/python2.7/site-packages/requests/models.py", line 752, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

This issue is here as a placeholder for the investigation.

**Comment by SeanTAllen** [comment]
That "twitter client" isn't the most robust of code but it gets the job done for an example. Running on my computer, it went for several hours without issue but... it wasn't written to be super resilient. I think in the case of the above error, it should close its connection and restart...
